# Generated by Django 4.1.2 on 2022-10-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0002_alter_user_bio_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
