# Generated by Django 4.1.2 on 2022-10-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0005_alter_post_author_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
